[menu __main IDEX]
name: IDEX

[menu __main IDEX toolchanger]
name: Activate Toolchanger Mode
method: printer.gcode.script
params: {"script":"ACTIVATE_TOOLCHANGER_MODE"}

[menu __main IDEX duplicationmode]
name: Activate Duplication Mode
method: printer.gcode.script
params: {"script":"ACTIVATE_DUPLICATION_MODE"}

[menu __main IDEX mirrormode]
name: Activate Mirror Mode
method: printer.gcode.script
params: {"script":"ACTIVATE_MIRROR_MODE"}

[menu __main IDEX activatee1]
name: Set E1 Active
method: printer.gcode.script
params: {"script":"T0"}

[menu __main IDEX activatee2]
name: Set E2 Active
method: printer.gcode.script
params: {"script":"T1"}